#!/bin/sh

TIMESTAMP=`date "+%b-%d-%Y-%T"`

# Sudoers
#--------

/usr/sbin/addsudo /usr/sbin/app-web-proxy-clear-cache app-web-proxy-core

# PAM check
#--------------------------------------------------------------------------

CHECK=`grep clearos/web_proxy.d /etc/pam.d/squid`
if [ -z "$CHECK" ]; then
    logger -p local6.notice -t installer "app-web-proxy-core - applying PAM configuration"
    [ -e /etc/pam.d/squid ] && cp /etc/pam.d/squid /var/clearos/web_proxy/backup/squid.pam.$TIMESTAMP
    cp /usr/clearos/apps/web_proxy/deploy/squid.pam /etc/pam.d/squid
fi

# There are /usr/libX references in the configuration files.  
#--------------------------------------------------------------------------

SYS_ARCH=`uname -m`

if [ "$SYS_ARCH" == "x86_64" ]; then
    WRONG_LIB="lib"
    CORRECT_LIB="lib64"
    LOG_LIB="64-bit"
else
    WRONG_LIB="lib64"
    CORRECT_LIB="lib"
    LOG_LIB="32-bit"
fi

CHECK=`grep "/usr/$WRONG_LIB/" /etc/squid/squid_auth.conf 2>/dev/null`

if [ -n "$CHECK" ]; then
    logger -p local6.notice -t installer "app-web-proxy-core - updating architecture to $LOG_LIB"
    sed -i -e "s/\/usr\/$WRONG_LIB/\/usr\/$CORRECT_LIB/" /etc/squid/squid_auth.conf
fi

# Configuration changes in ClearOS 7
#-----------------------------------

if [ -e /usr/lib/systemd/system/squid.service ]; then
    CHECK=`grep "^acl manager proto cache_object" /etc/squid/squid.conf 2>/dev/null`

    if [ -n "$CHECK" ]; then
        logger -p local6.notice -t installer "app-web-proxy-core - removing deprecated acl manager"
        sed -i -e '/^acl manager proto cache_object/d' /etc/squid/squid.conf
    fi

    CHECK=`grep "^acl localhost src" /etc/squid/squid.conf 2>/dev/null`

    if [ -n "$CHECK" ]; then
        logger -p local6.notice -t installer "app-web-proxy-core - removing deprecated acl localhost"
        sed -i -e '/^acl localhost src/d' /etc/squid/squid.conf
    fi

    CHECK=`grep "^acl to_localhost dst" /etc/squid/squid.conf 2>/dev/null`

    if [ -n "$CHECK" ]; then
        logger -p local6.notice -t installer "app-web-proxy-core - removing deprecated acl to_localhost"
        sed -i -e '/^acl to_localhost dst/d' /etc/squid/squid.conf
    fi

    CHECK=`grep '/squid_unix_group' /etc/squid/squid_auth.conf 2>/dev/null`

    if [ -n "$CHECK" ]; then
        logger -p local6.notice -t installer "app-web-proxy-core - changing squid_unix_group to ext_unix_group_acl"
        sed -i -e "s/\/squid_unix_group/\/ext_unix_group_acl/" /etc/squid/squid_auth.conf
    fi

    CHECK=`grep '/pam_auth' /etc/squid/squid_auth.conf 2>/dev/null`

    if [ -n "$CHECK" ]; then
        logger -p local6.notice -t installer "app-web-proxy-core - changing pam_auth to basic_pam_auth"
        sed -i -e "s/\/pam_auth/\/basic_pam_auth/" /etc/squid/squid_auth.conf
    fi

    CHECK=`grep '^access_log[[:space:]]*/var/log/squid/access.log[[:space:]]*squid' /etc/squid/squid.conf 2>/dev/null`

    if [ -n "$CHECK" ]; then
        logger -p local6.notice -t installer "app-web-proxy-core - updating access_log parameter"
        sed -i -e "s/access_log[[:space:]]*\/var\/log\/squid\/access.log/access_log stdio:\/var\/log\/squid\/access.log/" /etc/squid/squid.conf
    fi
fi

# Make sure Squid has permissions to Winbind pipe
#------------------------------------------------

if ! /usr/bin/id -n -G squid | grep -q "\<wbpriv\>"; then
    /usr/sbin/usermod -G $(id -Gn squid | tr ' ' ','),wbpriv squid
fi

# Run network configuration event on install/upgrade
#---------------------------------------------------

/var/clearos/events/network_configuration/web_proxy
