#!/bin/sh

#-------------------------------------------------------------------
# Load configuration
#-------------------------------------------------------------------

[ -e /etc/clearos/firewall.conf ] && source /etc/clearos/firewall.conf
[ -e /etc/sysconfig/squid ] && source /etc/sysconfig/squid
[ -e /etc/init.d/functions-automagic ] && source /etc/init.d/functions-automagic

#-------------------------------------------------------------------
# Generate error pages
#-------------------------------------------------------------------

ERRORFILES=`/bin/ls /usr/clearos/apps/web_proxy/deploy/templates/ERR_*template 2>/dev/null`
LANIP=`/bin/echo $AUTOMAGIC_LANIPS | /bin/cut -d ' ' -f 1`

if [ -n "$LANIP" ]; then
    for ERRORFILE in $ERRORFILES; do
        TARGET=`/bin/echo $ERRORFILE | sed 's/\.template$//' | sed 's/.*\///' `
        sed -e "s/PCN_LAN_IP/$LANIP/" $ERRORFILE > "/var/clearos/web_proxy/errors/$TARGET"
    done
fi

#-------------------------------------------------------------------
# Bail at this point if automagic is disabled
#-------------------------------------------------------------------

if [ "$AUTOMAGIC" == "off" ]; then
	exit 0
fi

#-------------------------------------------------------------------
# http_port configuration 
#-------------------------------------------------------------------

RELOAD=""

if [ "$SQUID_TRANSPARENT" == "on" ]; then
	TRANSPARENT=" transparent"
else
	TRANSPARENT=""
fi

echo "# Created automatically based on network configuration" > /etc/squid/squid_http_port.conf.clearos

for IP in $AUTOMAGIC_LANIPS 127.0.0.1; do
	echo "http_port $IP:3128$TRANSPARENT" >> /etc/squid/squid_http_port.conf.clearos
done

if diff /etc/squid/squid_http_port.conf.clearos /etc/squid/squid_http_port.conf >/dev/null 2>&1; then
    rm -f /etc/squid/squid_http_port.conf.clearos
else
    /usr/bin/logger -p local6.notice -t web_proxy "network change detected - updating port configuration" 
    mv /etc/squid/squid_http_port.conf.clearos /etc/squid/squid_http_port.conf
    RELOAD="yes"
fi

#-------------------------------------------------------------------
# LAN ACL definitions
#-------------------------------------------------------------------

echo "# Created automatically based on network configuration" > /etc/squid/squid_lans.conf.clearos

LANNETS=""

for LAN in $AUTOMAGIC_LANNETS; do
	LANNETS="$LAN $LANNETS"
done

if [ -n "$LANNETS" ]; then
	echo "acl webconfig_lan src $LANNETS $EXTRALANS" >> /etc/squid/squid_lans.conf.clearos
	echo "acl webconfig_to_lan dst $LANNETS $EXTRALANS" >> /etc/squid/squid_lans.conf.clearos
else
	echo "acl webconfig_lan src 192.168.0.0/16 10.0.0.0/8" >> /etc/squid/squid_lans.conf.clearos
	echo "acl webconfig_to_lan dst 192.168.0.0/16 10.0.0.0/8" >> /etc/squid/squid_lans.conf.clearos
fi

if diff /etc/squid/squid_lans.conf.clearos /etc/squid/squid_lans.conf >/dev/null 2>&1; then
    rm -f /etc/squid/squid_lans.conf.clearos
else
    /usr/bin/logger -p local6.notice -t web_proxy "network change detected - updating LAN configuration" 
    mv /etc/squid/squid_lans.conf.clearos /etc/squid/squid_lans.conf
    RELOAD="yes"
fi

#-------------------------------------------------------------------
# Reload if changes occurred
#-------------------------------------------------------------------

if [ "$RELOAD" == "yes" ]; then
    /usr/bin/logger -p local6.notice -t web_proxy "network change detected - reloading web proxy"
    /sbin/service squid reload >/dev/null 2>&1
fi
